package logos;

import java.util.ArrayList;

public class Problem {
	
	/*
	 * Problem types:
	 * 
	 * CONTRADICTION (includes 2 contradicting Links)
	 * MISSING_RESOURCE (includes 1 Logos object that isn't available) 
	 * UNKNOWN_REASON (includes 1 Link with unknown reason)
	 * UNKNOWN_PURPOSE (includes 1 Logos/Branch that LogOS checks for outgoing "in_order_to" Links)
	 * NO_INHERITANCE (not used)
	 * NO_DESCRIPTIONS (not used, redundant with UNKNOWN_PROPERTY)
	 * UNKNOWN_ACTION_REQUIREMENTS (includes 1 action Logos and 1 optional object Logos)
	 * UNKNOWN_PLACE (includes 1 object Logos and 1 optional description Logos)
	 * UNKNOWN_TIME_FUTURE/PAST (includes 2 Logos: object and action) 
	 * UNKNOWN_METHOD (includes 2 Logos: an action and an optional object)
	 * UNKNOWN_PROPERTY (includes 1 object Logos, 1 optional Link to a description Branch and 1 description Branch)
	 * UNKNOWN_OBJECT (includes 2 Logos: a subject and an action)
     * UNKNOWN_ACTION (includes 1 subject/actor Logos)
     * UNKNOWN_SUBJECT (includes 2 Logos: an action and an object)
     * PHILOSOPHICAL_QUESTION
     * COMMAND (includes 1 task_link from #SELF to the Branch containing the action to be accomplished)
     * IS_STATEMENT_TRUE (includes a List of interconnected Logos and Links - statement - to be proven)
     * UNKNOWN_QUANTITY (includes 1 subject Logos (can be a Branch) and 1 object Logos, 1 Link between them)
     * UNKNOWN_FIELD_VALUE (used for questions about color, shape etc.)
	 * 
	 * Basically, there are only 2 problems:
	 * 
	 * 1) not enough information (something is not well-defined)
	 * 2) direct contradiction (something is wrong)
	 * 
	 * In both cases, LogOS needs to interact with the user/world to find a solution.
	 * Thus, this class represents problems that cannot be solved by LogOS alone.
	 * Everything else is done by DatabaseInterface.
	 */
	
	public String type = "";
	public ArrayList<Link> linkCollection = new ArrayList<Link>();
	public ArrayList<Logos> logosCollection = new ArrayList<Logos>();
	public ArrayList<Branch> branchCollection = new ArrayList<Branch>();
	public double severity = 0;	// Problems in the buffer can be sorted by severity/importance
	public boolean internal = false;	// whether this Problem was generated by LogOS itself
	public boolean solved = false;

}